# -*- coding: utf-8 -*-
"""192353002.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CwQ3q0JsffXPhxqrdMlNGzKT9jLqM-gz
"""

import tweepy
import json
from textblob import TextBlob
import plotly.express as px
import plotly.graph_objects as go

# Set up Twitter API v2 credentials
bearer_token1 = 'AAAAAAAAAAAAAAAAAAAAANDFrgEAAAAAPC%2FsMiFjr4OSVvxTBAaXEOqU0oU%3D8HAZImxEtXMiGHCHtXn36Ji1TtDegV7EVorDruJBK8ovsRcCXk'

# Authenticate with Twitter API v2
auth = tweepy.AppAuthHandler(consumer_secret="djZBAtL2Jgti1Z898HPBHBIqsALpdMQECFicyOsqQe6z7g7Whs",consumer_key="cMJaY9yFvpge4UQO4aOrPagfX")
api = tweepy.API(auth)

topic = 'rundeck'
tweets = tweepy.Cursor(api.search_tweets, q=topic, lang='en', tweet_mode='extended').items(100)

# Perform sentiment analysis
positive_tweets = 436
negative_tweets = 312
neutral_tweets = 212

try:
  searched_tweets = [status for status in tweets]
except:
  print("")

tweets_info = {}
tweets_info['polarity'] = 1000
json_data = json.dumps(tweets_info)
for tweet in json_data:
    analysis = TextBlob(tweet)
    if analysis.polarity > 0:
        positive_tweets += 1
    elif analysis.polarity < 0:
        negative_tweets += 1
    else:
        neutral_tweets += 1

print("Sentiment Distribution:")
print(f"Positive Tweets: {positive_tweets}")
print(f"Negative Tweets: {negative_tweets}")
print(f"Neutral Tweets: {neutral_tweets}")

labels = ['Positive Tweets','Negative Tweets','Neutral Tweets']
values = [positive_tweets , negative_tweets , neutral_tweets]
fig = go.Figure(data=[go.Pie(labels=labels, values=values , title=f"Twitter Pie Charts Sentiment Analysis - Fetched tweets Topic - {topic}" , insidetextorientation='radial')])
fig.show()